### ISSUE TITLE
Not reconnecting when rebooting 1 AP

### ISSUE THREAD

**Issue by AciDCooL** [daniel-jong/esp8266_p1meter#31]
Hi I have a unifi setup at home with 5 APs, when I reboot them one by one the wemos disconnects from the wifi and never reconnects to the same or another AP. Has this todo with config or is this not implemented?

**Comment by daniel-jong** [comment]
Hi,

In the past I have had a setup with 2 Unify APs in range of my ESP, without to much issues.
Most of the Wifi stuff is handled by the WifiManager library.

Right now I'm running an [ESP32 based version](https://github.com/daniel-jong/esp8266_p1meter/tree/esp32) that uses a slightly different setup for Wifi management. So reproducing your issue is currently a bit hard for me.

You could try:
- Updating the WifiManager dependency, what version are you on right now? Updating this library might help?
- Connect to the ESP with an Serial connection so that you can read its logs.
